Score with cAdvisor metrics
intel/workload-collocation-agent pull request #512
Opened 2020-09-25 11:30 UTC by wacuuu

2020-09-28 07:28 UTC, Creatone commented on examples/kubernetes/monitoring/prometheus/cadvisor_prometheus_rule.score.yaml
> +      expr: 'sum(machine_cpu_cores) by (node)' # czy to naprawde ma byc suma wszystkich corow na clustrze
Consider translating this to English.

2020-09-28 07:28 UTC, Creatone commented on examples/kubernetes/monitoring/prometheus/cadvisor_prometheus_rule.score.yaml
> +      expr: 'ceil(sum(machine_dimm_capacity_bytes) by (node) / 1e9) and on(node) machine_nvm_capacity{mode="memory_mode"}==0' # to jest riski bo nie gwarantuje ze to ram
Consider translating this to English.

2020-09-28 07:46 UTC, felidadae reviewed
Not yet tested by me, i will seperately review rules files

2020-09-28 07:46 UTC, felidadae commented on examples/kubernetes/monitoring/prometheus/cadvisor.md
> +|0 | workload only allocates memory but doesn't use it or any cpu (perfect candidate) |
```suggestion
| -> 0 | workload which almost do not use any resources apart from allocating memory, perfect match for 2lm |
```

2020-09-28 07:46 UTC, felidadae commented on examples/kubernetes/monitoring/prometheus/cadvisor.md
> +3. *What bandwidth can we guarantee for an app in communication between CPU cache and memory?* (the bigger the better)
3 and 4 have the same meaning in my understanding.

Ad 3. what bandwidth is required by app. quarantee is a wrong choice of word

2020-09-28 07:46 UTC, felidadae commented on examples/kubernetes/monitoring/prometheus/cadvisor.md
> +The algorithm requires that there will be a way to identify all instances of a workload. That is there has to be for example a common label on all pods identifying the workload they belong to(see how
```suggestion
The algorithm requires that there will be a way to identify all instances of a workload. E.g. common label on all pods identifying the workload they belong to (see how "app" label is handled in example).
```

2020-09-28 07:46 UTC, felidadae commented on examples/kubernetes/monitoring/prometheus/cadvisor.md
> +Example workloads are in [this directory](../../workloads). Those are just reference applications used to test the solution. Only thing important for further explanation is the app label with value s
```suggestion
Workloads used by us in internal testing are located in [this directory](../../workloads). Only thing important for notice is the **app** label with value set to workload name. It is used to identify the workload in rules as mentioned in introduction.
```

2020-09-28 07:46 UTC, felidadae commented on examples/kubernetes/monitoring/prometheus/cadvisor.md
> +- `--perf_events_config=/etc/config/perf-hmem-cascadelake.json` is an argument pointing to perf config
```suggestion
- `--perf_events_config=/etc/config/perf-hmem-cascadelake.json` is an argument pointing to perf config, listing needed perf events
```

2020-09-28 07:50 UTC, felidadae commented on examples/kubernetes/monitoring/prometheus/cadvisor_prometheus_rule.score.yaml
> +      expr: 'sum(machine_cpu_cores) by (node)' # czy to naprawde ma byc suma wszystkich corow na clustrze
i believe that what states comment is not right, the expression is ok --> it is a sum of cores on a single node<

2020-09-28 13:57 UTC, wacuuu commented on examples/kubernetes/monitoring/prometheus/cadvisor.md
> +3. *What bandwidth can we guarantee for an app in communication between CPU cache and memory?* (the bigger the better)
I was trying to refer indirectly to 2 things that we gather: demand data.(rfo|rd) and separately bandwith bytes. I can remove one if required

2020-09-29 11:36 UTC, katarzyna-z commented on examples/kubernetes/monitoring/prometheus/cadvisor.md
> +The answer takes form of ratio how many times faster will the other resource(cpu, memory bandwidth or working set size) be saturated than the memory, for example if score is 1.25 it means that one of
missing space before bracket

2020-09-29 13:22 UTC, ppalucki requested changes

2020-09-29 13:43 UTC, wacuuu commented on examples/kubernetes/monitoring/cadvisor/kustomization.yaml
> +    newTag: magic-onion2
Yes, sorry this was commited as part of testing. will remember to clear this up

2020-09-29 13:48 UTC, ppalucki commented on examples/kubernetes/monitoring/prometheus/cadvisor.md
> +The algorithm requires that there will be a way to identify all instances of a workload. E.g. a common label on all pods identifying the workload they belong to(see how "app" label is handled in exam
the above issues is outdated, eventually in k8s we have:
- **controller-revision-hash** for both daemonsets and statefulsets e.g. `controller-revision-hash=58cdb6778b`
- **pod-template-hash** for deployments (e.g. `pod-template-hash: 58687784f9`) 

unfortunately using above labels doesn't carry any information about deploy/sts/daemonset name

@wacuuu are there any chances that we can join above "hash" with objects exposed by kube-state-metrics?

2020-09-29 13:49 UTC, wacuuu commented on examples/kubernetes/monitoring/prometheus/cadvisor.md
> +List of concepts and requirements to know before implementation explanation.
Point reader to the fact that one should get to know this part prior to deploying

2020-10-02 07:24 UTC, wacuuu commented on examples/kubernetes/monitoring/prometheus/cadvisor.md
> +The algorithm requires that there will be a way to identify all instances of a workload. E.g. a common label on all pods identifying the workload they belong to(see how "app" label is handled in exam
Well, controller revision hash is a label on infra container, so it could be added the same way as app label in example: map containers to pod by pod id and inherit all labels from pod container.

2020-10-14 08:09 UTC, felidadae requested changes
2m ---> 7d
test after changes --- remove rules --- wait 5 minutes -- add rules wait 10 minutes check score

2020-10-15 09:07 UTC, felidadae approved these changes

2020-10-15 10:23 UTC, ppalucki approved these changes
great work!

2020-10-15 10:25 UTC, merged