Improvement Kubernetes docs
intel/workload-collocation-agent pull request #514
Opened 2020-10-01 08:23 UTC by Damenus

2020-10-01 18:03 UTC, ppalucki requested changes
some typos

2020-10-01 18:03 UTC, ppalucki commented on examples/kubernetes/monitoring/wca/README.md
> +   You have to replace `DOCKER_REPOSITORY_URL` variable to yours own docker registry.
s/yours/your/

2020-10-02 06:23 UTC, wacuuu commented on examples/kubernetes/monitoring/wca/DEVEL.md
> +ADVANCE WCA DEPLOY
Perhaps it should be ADVANCED?

2020-10-02 06:23 UTC, wacuuu commented on examples/kubernetes/monitoring/wca/DEVEL.md
> +Workload Collocation Agent required private key and certificate to connect with kubelet.
s/required/requires/

2020-10-02 06:23 UTC, wacuuu commented on examples/kubernetes/monitoring/wca/DEVEL.md
> +WCA OUTSIDE KUBERNETES
WCA OUTSIDE OF KUBERNETES

2020-10-02 06:23 UTC, wacuuu commented on examples/kubernetes/monitoring/wca/DEVEL.md
> +Optionally, you can use token to connect to Kube API Server, while WCA is using outside pod.
I don't get this part. WCA is running in a pod, yet it's not a part of kubernetes?

2020-10-02 06:23 UTC, wacuuu commented on examples/kubernetes/monitoring/wca/README.md
> +   Workload Collocation Agent required existing `wca` namespace and label `monitoring=wca` on nodes,
requires wca namespace to exist

2020-10-02 06:23 UTC, wacuuu commented on examples/kubernetes/monitoring/wca/README.md
> +      Label can be crated by using kubectl by a following command:
I think it should be "by the following command"

2020-10-02 06:23 UTC, wacuuu commented on examples/kubernetes/monitoring/wca/README.md
> +      If you want deploy wca on all nodes, you can delete affinity in daemonset spec.
If you want **to** deploy

2020-10-02 06:23 UTC, wacuuu commented on examples/kubernetes/monitoring/wca/README.md
> +After deploy wca, you can deploy Prometheus operator to collect metrics from wca and visual them in Prometheus.
After deploying wca

2020-10-02 06:23 UTC, wacuuu commented on examples/kubernetes/monitoring/wca/daemonset.yaml
> +      # or debugging purpose, alternative way to nodeAffinity selection nodes
missing f in potential for in the beginning of the line?

2020-10-02 06:25 UTC, Damenus commented on examples/kubernetes/monitoring/wca/README.md
> +Below instruction is about run wca as DaemonSet on cluster. This way uses kustomize to deploy all components.
fixed

2020-10-02 06:25 UTC, Damenus commented on examples/kubernetes/monitoring/wca/README.md
> +Kustomize is available from kubectl 1.14.
added

2020-10-02 06:25 UTC, Damenus commented on examples/kubernetes/monitoring/wca/README.md
> +   Workload Collocation Agent required existing `wca` namespace and label `monitoring=wca` on nodes,
fixed

2020-10-02 06:25 UTC, Damenus commented on examples/kubernetes/monitoring/wca/README.md
> +   You have to replace `DOCKER_REPOSITORY_URL` variable to yours own docker registry.
fixed

2020-10-02 06:29 UTC, Damenus commented on examples/kubernetes/monitoring/wca/DEVEL.md
> +ADVANCE WCA DEPLOY
Fixed, it sounds better

2020-10-02 06:30 UTC, Damenus commented on examples/kubernetes/monitoring/wca/DEVEL.md
> +Workload Collocation Agent required private key and certificate to connect with kubelet.
fixed

2020-10-02 06:30 UTC, Damenus commented on examples/kubernetes/monitoring/wca/DEVEL.md
> +WCA OUTSIDE KUBERNETES
fixed

2020-10-02 06:31 UTC, Damenus commented on examples/kubernetes/monitoring/wca/README.md
> +      Label can be crated by using kubectl by a following command:
fixed

2020-10-02 06:31 UTC, Damenus commented on examples/kubernetes/monitoring/wca/README.md
> +      If you want deploy wca on all nodes, you can delete affinity in daemonset spec.
fixed

2020-10-02 06:32 UTC, Damenus commented on examples/kubernetes/monitoring/wca/README.md
> +After deploy wca, you can deploy Prometheus operator to collect metrics from wca and visual them in Prometheus.
fixed

2020-10-02 06:32 UTC, Damenus commented on examples/kubernetes/monitoring/wca/daemonset.yaml
> +      # or debugging purpose, alternative way to nodeAffinity selection nodes
yeap, fixed

2020-10-02 06:38 UTC, Damenus commented on examples/kubernetes/monitoring/wca/README.md
> +   Build Docker image and push to private repo. You can use make command to this. Like in example below.
removed

2020-10-02 06:45 UTC, Damenus commented on examples/kubernetes/monitoring/wca/DEVEL.md
> +Optionally, you can use token to connect to Kube API Server, while WCA is using outside pod.
I mean that WCA isn't in K8S network (don't get certs and token, cannot connect to services which work only inside the network) and you must prepare all as like as you outside the cluster

2020-10-02 08:39 UTC, ppalucki approved these changes

2020-10-02 08:58 UTC, merged