Memcached-mutilate hmem workload
intel/workload-collocation-agent pull request #519
Opened 2020-10-05 07:09 UTC by Damenus

2020-10-07 07:19 UTC, felidadae commented on examples/kubernetes/workloads/memcached-mutilate/medium-wss/kustomization.yaml
> +  - value=1000            # keys 30B + value 1000B * 35.1M <= 40GB
lacking paranthesis

2020-10-07 11:47 UTC, ppalucki requested changes

2020-10-07 11:47 UTC, ppalucki commented on examples/kubernetes/workloads/memcached-mutilate/_hmem/pmem/kustomization.yaml
> +    generator: dram
there is bug here, I messed up, and it should be "generator: pmem", Marta is going to fix that for redis and you should for memcached

2020-10-09 07:41 UTC, Damenus commented on examples/kubernetes/workloads/memcached-mutilate/_hmem/pmem/kustomization.yaml
> +    generator: dram
Fixed

2020-10-09 07:41 UTC, Damenus commented on examples/kubernetes/workloads/memcached-mutilate/medium-wss/kustomization.yaml
> +  - value=1000            # keys 30B + value 1000B * 35.1M <= 40GB
Fixed

2020-10-09 09:04 UTC, ppalucki approved these changes

2020-10-09 09:32 UTC, merged