After WSS changes updates in Score, Also updates for HMEM specific.
intel/workload-collocation-agent pull request #523
Opened 2020-10-06 12:37 UTC by felidadae

2020-10-07 11:49 UTC, ppalucki requested changes

2020-10-07 11:49 UTC, ppalucki commented on docs/score_algorithm.rst
> +A little changes must be made to adjust the rules for **2LM** PMEM mode. By default the rules file is
As agreed please the default values for 2LM and provide instruction for generating scores for HMEM (unless Tomasz respond with other decision).

2020-10-08 08:59 UTC, ppalucki approved these changes

2020-10-08 08:59 UTC, ppalucki commented on docs/score_algorithm.rst
> +Results for our testing workloads
s/testing/example

2020-10-08 08:59 UTC, ppalucki commented on docs/score_algorithm.rst
> +#################
Please add: Proper visualization requires Grafana with boom table plugin (from [here](https://grafana.com/grafana/plugins/yesoreyeram-boomtable-panel))

2020-10-08 08:59 UTC, ppalucki commented on docs/score_algorithm.rst
> +Igoring tasks first N minutes of execution
Please run "spell checker", because there is type here: s/Igoring/Ignoring/

2020-10-08 08:59 UTC, ppalucki commented on docs/score_algorithm.rst
> +We on purpose ignores first N minutes (by default N=30) of execution of each task.
s/We/Solution/ or s/ignores/ignore/

2020-10-08 08:59 UTC, ppalucki commented on docs/score_algorithm.rst
> +- ignore any costly initialization phase, which could result in overestimatation of parameters
append "," at the end of first point

2020-10-08 08:59 UTC, ppalucki commented on docs/score_algorithm.rst
> +Drawback of the approach is that we will not detect workloads with only short living tasks.
s/detect/characterize/

2020-10-08 08:59 UTC, ppalucki commented on docs/score_algorithm.rst
> +The algorithm requires that there will be a way to identify all instances of a workload. E.g. a common
Please describe it using k8s nomenclature/domain.

- instance - Kubenrete's Pod
- workload - Kubenrete's Controller e.g. StatefulSet of DaemonSet  

Solution assumes that Pod have similar resource pattern/usage characteristics.

2020-10-08 09:06 UTC, ppalucki requested changes

2020-10-08 09:06 UTC, ppalucki commented on docs/score_algorithm.rst
> +one can use built-in controllers labels as described [here.](https://github.com/kubernetes/kubernetes/issues/47554)
Described here is wrong, it is just an issue that tries to have uniform label for hash templates, but it sill different for SS,Deploy and DS and lacks name of the app or workload.

You should mention: 

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

as recommended label scheming.

2020-10-08 10:32 UTC, felidadae commented on docs/score_algorithm.rst
> +A little changes must be made to adjust the rules for **2LM** PMEM mode. By default the rules file is
fixed

2020-10-08 11:07 UTC, wacuuu commented on docs/score_algorithm.rst
> +as peak (**0.95** quantile) value using **quantile** and **quantile_over_time** prometheus functions:
quantile is to get rid of peaks. would use word max instead of peak, or at least explain why quantile

2020-10-08 11:07 UTC, wacuuu commented on docs/score_algorithm.rst
> +- our method of estimating WSS (working set size) uses /proc/{pid}/smaps kernel API, which may have noneglicable overhead
s/noneglicable /non negligible is this what you meant?

2020-10-08 11:07 UTC, wacuuu commented on docs/score_algorithm.rst
> +one can use built-in controllers labels as described [here.](https://github.com/kubernetes/kubernetes/issues/47554)
That is a good point, maybe change this part a bit so that is shows a "good practices approach" to labeling and emphasise that app label is heavily used to group workload telemetry in rules

2020-10-08 12:08 UTC, ppalucki approved these changes

2020-10-08 12:31 UTC, merged