Add tests for cAdvisor's perf
intel/workload-collocation-agent pull request #550
Opened 2020-11-06 10:22 UTC by kwisniewski98

Signed-off-by: Wisniewski, Krzysztof2 Krzysztof2.Wisniewski@intel.com

2020-11-09 18:16 UTC, Damenus requested changes

2020-11-10 13:45 UTC, Creatone requested changes

2020-11-10 13:45 UTC, Creatone commented on tests/cadvisor/Jenkinsfile
> +        stage('Run pmbench') {
The stage before you "Running pmbench". Maybe consider naming it "Checking pmbench" or something else.

2020-11-12 09:29 UTC, Damenus commented on tests/cadvisor/Jenkinsfile
> +        stage('Run pmbench') {
I wonder if @kwisniewski98 you should delete stage 'Running pmbench' because it is not necessary in my opinion to run extra pmbench, because this stage has no tests.

2020-11-12 09:31 UTC, Damenus requested changes

2020-11-12 09:31 UTC, Damenus commented on tests/cadvisor/Jenkinsfile
> +                          ${CADVISOR_IMAGE} -housekeeping_interval=3s  -v 4  '-perf_events_config=/perf.json' >> ${CADVISOR_LOGS_FILE} & '''
One '-' in  -housekeeping_interval=3s is enough?

2020-11-12 09:35 UTC, Creatone commented on tests/cadvisor/Jenkinsfile
> +                          ${CADVISOR_IMAGE} -housekeeping_interval=3s  -v 4  '-perf_events_config=/perf.json' >> ${CADVISOR_LOGS_FILE} & '''
In golang it's possible. 
Check: https://golang.org/pkg/flag/#hdr-Command_line_flag_syntax

2020-11-12 10:51 UTC, Damenus commented on tests/cadvisor/Jenkinsfile
> +                          ${CADVISOR_IMAGE} -housekeeping_interval=3s  -v 4  '-perf_events_config=/perf.json' >> ${CADVISOR_LOGS_FILE} & '''
ok

2020-11-17 10:54 UTC, Creatone approved these changes

2020-11-17 10:56 UTC, Damenus approved these changes

2020-11-17 10:57 UTC, merged