Experiment HMEM
intel/workload-collocation-agent pull request #551
Opened 2020-11-06 22:13 UTC by Damenus

2020-11-26 13:45 UTC, mmucek95 requested changes

2020-11-26 13:45 UTC, mmucek95 commented on examples/kubernetes/monitoring/wca/wca-config.yaml
> +#  event_names:
This should be commented out for experiment purposes but please do not commit this to the repo.

2020-11-26 13:45 UTC, mmucek95 commented on examples/kubernetes/monitoring/wca/wca-config.yaml
> +    # grupa 1
Please write in english.

2020-11-26 13:45 UTC, mmucek95 commented on examples/kubernetes/scripts/analyzer/metrics.py
> +    # Metric.PLATFORM_VMSTAT_NUMA_HINT_FAULTS,
Please remove unused

2020-11-26 13:45 UTC, mmucek95 commented on examples/kubernetes/scripts/analyzer/metrics.py
> +    # free vs toptier watermark (when free(solid) below toptier mark wakeup kswapd/toptier_reclam)
Please remove unused code instead of commenting it out.

2020-11-26 19:37 UTC, Damenus commented on examples/kubernetes/monitoring/wca/wca-config.yaml
> +#  event_names:
I reverted the changes

2020-11-26 19:37 UTC, Damenus commented on examples/kubernetes/scripts/analyzer/metrics.py
> +    # Metric.PLATFORM_VMSTAT_NUMA_HINT_FAULTS,
as above

2020-11-26 19:37 UTC, Damenus commented on examples/kubernetes/monitoring/wca/wca-config.yaml
> +    # grupa 1
as above

2020-11-26 19:37 UTC, Damenus commented on examples/kubernetes/scripts/analyzer/metrics.py
> +    # Metric.PLATFORM_VMSTAT_NUMA_HINT_FAULTS,
Deleted

2020-11-27 14:05 UTC, mmucek95 approved these changes

2020-11-30 07:39 UTC, felidadae approved these changes

2020-11-30 16:22 UTC, merged