Add resctrl test for cAdvisor
intel/workload-collocation-agent pull request #559
Opened 2021-02-12 16:00 UTC by kwisniewski98

2021-02-15 13:02 UTC, Creatone requested changes

2021-02-15 13:02 UTC, Creatone commented on tests/cadvisor/test_cadvisor_rdt.py
> +    use_cgroup = os.getenv("USE_CGROUP")
This can lead to misunderstanding code because Resctrl control groups are something different than the cgroups. Please change it to `use_control_group`.

2021-02-15 13:02 UTC, Creatone commented on tests/cadvisor/test_cadvisor_rdt.py
> +        cgroup = f.read().strip("\n").replace("/", "-")
This can lead to misunderstanding code because Resctrl control groups are something different than the cgroups. Please change it to `control_group`.

2021-02-17 09:42 UTC, kwisniewski98 commented on tests/cadvisor/Jenkinsfile
> +    sleep ((params.TEST_LENGTH.toInteger() - PAUSE_BETWEEN_CONTAINERS_STARTUP.toInteger() - 5) / 2)
I've added comment in code

2021-02-17 09:43 UTC, kwisniewski98 commented on tests/cadvisor/Jenkinsfile
> +                 stage("Deploy cadvisor"){
Changed

2021-03-22 07:38 UTC, Creatone approved these changes

2021-03-22 08:16 UTC, merged